target "JMian"
pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'SDCycleScrollView'
pod 'YYText'
pod ‘YYCache’
pod 'PrintBeautifulLog'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'AgoraRtcEngine_iOS'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'VIMediaCache'
pod 'HXWeiboPhotoPicker', '~> 2.1.5'
pod 'IQKeyboardManager', '3.3.7'
pod 'STPickerView', '2.4'
pod 'WechatOpenSDK'
pod 'MMLayout','0.2.0'
pod 'ReactiveObjC'
pod 'iVersion'
pod 'Toast'
pod 'ISVImageScrollView'
pod 'TXIMSDK_iOS'